llm:
  provider: OPENAI

  meta:
    model: deepseek-chat
    max_tokens: 8096
    temperature: 0.2

prompt:
  normalize_prompts: true
  summary_prompt_files: [ ./prompts/summary.md ]

review:
  mode: ADDED_AND_REMOVED_WITH_CONTEXT
  inline_tag: "#ai-review-ds:inline"
  inline_reply_tag: "#ai-review-ds:inline-reply"
  summary_tag: "#ai-review-ds:summary"
  summary_reply_tag: "#ai-review-ds:summary-reply"
  context_lines: 25

vcs:
  provider: GITHUB

  http_client:
    timeout: 120
    api_url: https://api.github.com

